Assorted style tweaks
scb-dmc/dealer-locator pull request #8
Opened 2020-10-14 20:43 UTC by alfajor

This increases the dealer list width and adds a slight buffer between the list container and the footer.

2020-10-14 20:46 UTC, apsummers approved these changes

2020-10-15 16:13 UTC, thundercat1 requested changes
see comments - just want to make sure that we only make changes in the dealer-locator core if we're 99% sure that they're changes that should be applied to every site it's used on. The default should be to make style & theming changes in the site that's using the package

2020-10-15 16:13 UTC, thundercat1 commented on src/index.js
> +  max-height: calc(100vh - 300px);
Does this mean the dealer list will be shorter than the map, or does it shorten the entire map? Also consider if this component were to get used on a page without a footer, or with additional elements on the page - we don't want to constrain the core code of dealer-locator repository to only working on the two sites we have migrated so far

2020-10-15 16:13 UTC, thundercat1 commented on src/theme.js
> +    menuSlideoutWidth: "352px",
is this a change we're happy with having on Reserve too?

2020-10-15 22:53 UTC, thundercat1 approved these changes

2020-10-15 23:19 UTC, thundercat1 approved these changes

2020-10-16 15:53 UTC, merged